import { GUIDE_BUILT_REV, type GuideSection } from '../types'

export const plays: GuideSection = {
  id: 'plays',
  num: 5,
  title: 'The Plays',
  tagline: 'Eight condition templates + the A-setup chain.',
  asBuiltRev: GUIDE_BUILT_REV,
  blocks: [
    {
      kind: 'cards',
      cards: [
        {
          title: 'reclaim',
          body: 'Setup: level touched → price closes back on the original side → confirm: 1×5m close beyond (rule 1x5m_close) or a 1m-MSS (rule 1m_mss). NEVER 2×5m (2x5m_reserved — the double close is legal only on waterfall-class plays). The planner writes it when a level was lost and re-taken. Expectancy: the bread-and-butter retest play.',
          tag: 'play 1',
        },
        {
          title: 'hold',
          body: 'Setup: price holds a level → confirm: time_hold (price holds beyond the ref for ACCEPT_HOLD_MIN = 10 minutes of 1m closes, no close back across) or 1x5m_close as the fallback. Written when the plan expects support/resistance to keep working.',
          tag: 'play 2',
        },
        {
          title: 'sweep_reclaim',
          body: 'Setup: level swept (liquidity taken) → close back inside → the SPLIT contract (E4): leg 1 = touch at the sweep ref (resting limit, no confirm), leg 2 = 1m-MSS or the reclaim 1×5m close — never 2×. The house play at ONH/ONL. Expectancy: week 0% / −192 when misplayed as fade-the-poke; the sweep first is what makes it valid.',
          tag: 'play 3',
        },
        {
          title: 'reject',
          body: 'Setup: first touch rejected at a zone → confirm: TOUCH at the level (rule touch) — fades never close-confirm (fade_requires_touch). Structure stop ≥2 ticks beyond the level; limit at the level. NY stat: 75% win / +665 (the best measured condition×session pair).',
          tag: 'play 4 · 75%',
        },
        {
          title: 'acceptance',
          body: 'Setup: closes through a level and holds → confirm: time_hold (10 min of 1m closes) or 1x5m_close. HOUSE RULE: acceptance requires a PRIOR sweep + displacement or the plan skips it (0% win evidence for bare acceptance).',
          tag: 'play 5',
        },
        {
          title: 'breakout_retest',
          body: 'Setup: break above/below → first retest holds → confirm: touch at the retest level + the STOP-ENTRY fallback (no retest within RETEST_WAIT_BARS = 6 bars → stop-entry beyond the break candle); 1x5m legal for the break leg. The ONH breakout play when price is at the top of the stack.',
          tag: 'play 6',
        },
        {
          title: 'fvg_entry',
          body: "Setup: the A-setup's finish — displacement leaves a gap → first retrace INTO the FVG → confirm: touch at the gap band. entry_mode ce by default (edge only for A-grade HTF-confluent origins); stop beyond the sweep extreme; T1 = first opposing pool; runner = the draw. chain_after links it to its sweep_reclaim. FVG DEMAND (A2c): a fresh machine gap matching your bias expects an fvg_entry — or a one-line reason why not.",
          tag: 'play 7',
        },
        {
          title: 'breakdown_continue',
          body: 'Setup: price closes BELOW a broken level with displacement ≥ 1.0×ATR5m (BD_MIN_DISP_ATR) and no reclaim close → the waterfall SHORT. BD_MIN_CLOSES = 1: ONE confirming close + displacement is the floor (the double close is gone). Two-leg confirm: leg 1 = the breakdown close, leg 2 = the retest that FAILS to reclaim. entry_mode pullback rests at the broken level (ARM path); immediate is AI-path (market entry on the confirming close through the FULL gate chain — no arm; arms stay pullback-only). Born 2026-08-28: the −347pt NY crash — bias right, but NO plan-legal continuation short existed.',
          tag: 'play 8 · −347',
        },
        {
          title: 'breakup_continue',
          body: 'The LONG mirror: closes ABOVE a broken level with displacement ≥ 1.0×ATR5m, no reclaim → continuation long; BD_MIN_CLOSES = 1, same two-leg confirm. entry_mode pullback = arm at the broken level; immediate = AI-path market entry on the confirming close (full gate chain, no arm). 2x5m_close is legal ONLY on this class — everywhere else it is 2x5m_reserved.',
          tag: 'play 8b',
        },
      ],
    },
    { kind: 'h', text: 'THE ENTRY LAW (per condition — machine-enforced)' },
    {
      kind: 'code',
      title:
        'one table, one chokepoint — the validator REJECTS violations by name',
      lines: [
        'reject / fvg_entry    → touch ONLY · fade_requires_touch · stop ≥2 ticks beyond',
        'sweep_reclaim         → leg-1 touch at the sweep ref, leg-2 1m_mss (1x5m_close alt)',
        'reclaim               → 1x5m_close | 1m_mss · 2x5m_reserved',
        'breakout_retest       → touch at the retest + stop-entry fallback · 1x5m_close legal',
        'acceptance / hold     → time_hold | 1x5m_close · 2x5m_reserved',
        'breakdown/breakup     → 1 confirming close + displacement (BD_MIN_CLOSES=1)',
        '                       → 2x5m_close legal ONLY here',
        '',
        '15m confirms are DEAD — confirm_rule_15m_removed (rejected by name).',
        'Tokens are spelled the way the field accepts them: confirm.rule takes',
        'touch|1x5m_close|2x5m_close|1m_mss|time_hold, while death/flip.rule is a',
        'SEPARATE enum (2x5m|5m_close). Never move a token between the two.',
      ],
    },
    {
      kind: 'h',
      text: 'ARM SPLIT vs ARM SINGLE (class 38 · normalizer class 39)',
    },
    {
      kind: 'code',
      title: 'legs[] belong to sweep_reclaim and nothing else',
      lines: [
        'sweep_reclaim   → SPLIT: EXACTLY 2 legs · confirm=touch at the sweep ref',
        '                  leg 1 rests (wait_confirm false) · leg 2 chains (true)',
        '                  leg 2 rule = confirm2.rule ∈ 1m_mss | 1x5m_close',
        '                  top-level entry/stop/target mirror leg 1',
        'everything else → SINGLE: arm{} with wait_confirm:true and NO legs',
        '                  (breakdown_continue, breakup_continue, reject, fvg_entry)',
        'breakout_retest → never arms at all (GAR-F4)',
        '',
        'Class 39 (owner ruling 2026-09-01): if the model STILL puts legs on a',
        'non-sweep condition, the machine drops the legs array, re-validates the',
        'single top-level arm and proceeds with a ⚖ WARN naming every dropped',
        'leg — instead of burning a retry. If the single arm is itself invalid',
        'the plan is rejected UNCHANGED with the original reason. Never a leg',
        'synthesized; never the reverse (one leg on sweep_reclaim stays a reject).',
        'Counter: arms_normalized_class39 (recorded, survives restarts).',
        '',
        'Why it is in the guide: 35 of 121 validator rejects in the 72h to',
        '2026-09-01 were legs on a non-sweep condition, and the prompt never',
        'said the rule. Class 38 makes the prompt state every restriction the',
        'validator enforces; the boot line 📜 prompt/validator contract counts',
        'them and fails loudly if one goes unstated.',
      ],
    },
    { kind: 'h', text: 'The new confirm rules' },
    {
      kind: 'code',
      title: '1m-MSS and time_hold — the E5/E6 primitives',
      lines: [
        '1m_mss    : last confirmed 1m fractal swing (k=2) broken by a 1m CLOSE',
        '            beyond it with displacement ≥ MSS_MIN_DISP_ATR × ATR5m (0.5).',
        '            Closed bars only — a wick beyond the swing NEVER counts.',
        '            Renders "1m-MSS: MET/NOT-MET (swing <px> @<t>)".',
        'time_hold : price holds beyond the ref for ACCEPT_HOLD_MIN (10) minutes',
        '            of 1m closes with no close back across — for acceptance/hold.',
        'stop_entry: the breakout-retest fallback — a STOP-MARKET entry beyond the',
        '            break candle after RETEST_WAIT_BARS (6) no-retest bars,',
        '            STOP_ENTRY_OFFSET_TICKS (2) beyond. Gated on STOP_ENTRY_SEAM',
        '            (owner-enabled only after the far-side AddOn proves the frame).',
      ],
    },
    { kind: 'h', text: 'Entry-mechanics knobs' },
    {
      kind: 'p',
      text: "BD_MIN_CLOSES (1) · BD_MIN_DISP_ATR (1.0) · MSS_MIN_DISP_ATR (0.5) · ACCEPT_HOLD_MIN (10) · STOP_ENTRY_OFFSET_TICKS (2) · RETEST_WAIT_BARS (6) · STOP_ENTRY_SEAM (off). Default confirm = 1x5m_close; a sweep_reclaim arm may split into TWO child orders (leg 1 touch + leg 2 chained) — either leg's stop-out cancels the sibling's unfilled order (no doubling into a failed level).",
    },
    { kind: 'h', text: 'THE A-SETUP (the chained play)' },
    {
      kind: 'code',
      title: 'sweep → displacement → FVG retrace, at a fresh Tier-1 origin',
      lines: [
        'S1 sweep_reclaim : liquidity pool swept (ONH/EQH) + reclaim close',
        '        │  chain_after: S1',
        '        ▼',
        'S2 fvg_entry    : the displacement gap retraces into the FVG band',
        '        entry_mode = ce (edge only for A-grade HTF-confluent origins)',
        '        stop beyond the sweep extreme · T1 = first opposing pool',
        '        runner = the draw (nearest opposing liquidity beyond T1)',
        '',
        'a bare fvg_entry with NO sweep precursor at a non-A/B origin',
        'gets a WARN at write — the raw-FVG null (40k sample) says it',
        'has no standalone edge.',
      ],
    },
    { kind: 'h', text: 'No-trade is a trade' },
    {
      kind: 'p',
      text: 'The planner is now SHOWN which levels can carry a waterfall: the facts block states the displacement floor for the cycle (1.0×ATR5m, resolved) and, per seated level, the measured displacement since its break — or "none — no break". A breakdown_continue authored below the floor is refused at write, and before 2026-09-03 that number was enforced without ever being stated. Sitting out is a position. The gates the planner is taught: balance day → edges only or skip · opening gap >1.2×ATR or outside-range open → never fade · no A/B zone in reach AND no pool swept by 10:30 ET → skip the day · lunch 11:30–13:30 ET → no entries · Tier-1 news → stand aside. A real skip looks like: "no_trade: balance day — no A/B zone in reach by 10:30 ET, skip" — that is a decision, not a failure.',
    },
  ],
}
