import { GUIDE_BUILT_REV, type GuideSection } from '../types'

export const status: GuideSection = {
  id: 'status',
  num: 10,
  title: 'Status & Signals',
  tagline: 'Every indicator strip, banner, and log line — decoded.',
  asBuiltRev: GUIDE_BUILT_REV,
  blocks: [
    { kind: 'h', text: 'Where this page comes from' },
    {
      kind: 'p',
      text: "The UI you are reading is served by the bot's own process at http://localhost:8080. That is the production path and the one this Guide assumes. Until 2026-09-03 there was no production path at all: the interface was served by a Vite DEVELOPMENT server on port 3000, started by hand, supervised by nothing, and the built bundle on disk had been stale since 08-31 while the Go server answered 404 at its own root. A reboot of the machine, or anything that stopped that one node process, took the whole interface with it and left the bot trading blind to its operator. Port 3000 still works and is still the right thing to use while developing — it rebuilds on save — but nothing depends on it any more.",
    },
    {
      kind: 'p',
      text: "The boot log says which path is live and how old the bundle is: '🖥 ui: served-by=go-static build=<timestamp>'. If that bundle is older than the binary running it, the line adds STALE and how far behind it is, and it is logged as a warning rather than as information — because a stale bundle means the screen is showing you a build that is not the one making your trading decisions. 'served-by=none' means no bundle was found at web/dist; the API keeps working and only the interface is missing, which is why the bot does not refuse to start over it.",
    },
    { kind: 'h', text: 'What the E8 side-table can be used for' },
    {
      kind: 'p',
      text: "The A/B counterfactual table records what a confirm rule WOULD have done. Until 2026-09-03 every short row in it was arithmetic across two price spaces: the replay mirrored stop/target into negative prices so the excursion signs read nicely, while the fill and the stored bracket stayed real — so risk came out as 58 430 instead of 21.50 and RR sat pinned near −1. Measured with direction read from the plan: 121 short rows, 109 with a broken RR; all 67 long rows were always clean. The boot line now states what survives: 'e8: rows=188 usable=55 · unrecomputable fill-bar=54 no-inputs=12'. USABLE is the only count a ruling may rest on. The 54 fill-bar rows keep their numbers and are labelled, because the same bug also broke the close-rule comparison — their fill came from the wrong bar, and clean arithmetic on a wrong fill is a precise answer about the wrong moment.",
    },
    { kind: 'h', text: 'The tree guard — what watches the deploy tree' },
    {
      kind: 'p',
      text: 'A background check runs every 60 seconds against /home/hoang/nofx and reports four things: is the tree clean, are the shipped safety symbols still present, does deploy/RELEASE agree with the binary that is actually running, and is anything committed but unpushed. It writes a verdict to ~/nofx-backups/tree-guard/state and a line to the user journal (journalctl --user -u nofx-tree-guard.service).',
    },
    {
      kind: 'p',
      text: 'It exists because on 2026-09-02 an editor Save-All wrote six stale buffers over the deploy tree and deleted 596 lines of shipped safety code across four waves — the stop floor, the corrected-P&L readers, arm-leg normalisation, and the real order-book reader. Nothing detected it. It sat there for three hours and twenty minutes and was found by accident. The tree survived only because nobody happened to build from it in that window.',
    },
    {
      kind: 'callout',
      title: 'What the guard will never do',
      items: [
        {
          title: 'It never repairs',
          body: 'It runs no git command that writes — no checkout, restore, reset, stash or clean. A guard that repaired the tree would be a second thing writing to it without being asked, which is exactly the problem it was built to detect. It tells you; you decide. A test greps the script to keep that true.',
        },
        {
          title: 'It does not close the hole',
          body: 'An editor can overwrite the deploy tree at any moment, and no file in this repo can stop it — the worktree rule and the lock file both govern automated agents, and an editor is not one. The guard shortens discovery from hours to a minute. The actual fix is to stop opening /home/hoang/nofx in an editor and open a worktree instead. That is a habit, not a setting.',
        },
        {
          title: 'A dirty tree is not always an alarm',
          body: 'A cutover legitimately dirties the tree when it writes the RELEASE file before the swap. If the lock file names a process that is genuinely alive with a fresh heartbeat, that dirt reads as INFO and the files are still listed. A dead process in the lock file does NOT buy silence — that is the signature the guard is looking for.',
        },
      ],
    },
    { kind: 'h', text: 'The boot ledger, line by line' },
    {
      kind: 'code',
      title: 'the lines printed at startup, in order',
      lines: [
        '🔐 BOOT INTEGRITY OK — rev <sha> [+dirty] · built <ts>',
        '🧾 P&L surfaces: <N> aggregators strict-corrected, 0 raw (corrected-column guard) — every P&L figure the model and the dashboard read is pnl_corrected; unresolved rows are counted and excluded, never coerced',
        '🛑 exits: stop=max(anchor+clr, 1.5×ATR5m) · anchor_max=3.0×ATR5m · BE=off · trail=off · size=1 · re-arm-after-sweep=on (0B) — the whole exit posture in one line',
        '⏱ wakes: cutoff=25m(enforce) cooldown=30m(enforce, fast-market≥1.5×ATR exempt) cross-session=on stale-arm-expiry=on (class 47) — ENFORCING since 2026-09-03: a level_event wake with under 25 min to the flat is SKIPPED (its read would land after the last-entry gate closes), and so is one within 30 min of the last wake-authored version — UNLESS price has drifted ≥ FAST_MARKET_ATR (1.5×) from the plan being traded, which bypasses the cooldown and logs "cooldown bypassed: fast market <drift>×ATR". The 25-min cutoff is never exempted: a re-plan with 20 minutes left is a re-plan with 20 minutes left, fast or not. Scheduled reads, death re-plans and owner resets are untouched. cross-session defers WAKES (never scheduled reads) while a planner stream is open; stale-arm expiry retires never-placed arms from superseded plan versions',
        '    · expected <sha> · goldens PASS      ← code matches deploy record',
        '📜 planner playbook: playbook=v2 bias_tree=on …',
        '🛡 plan facts guards: 0-side + empty map fail-closed …',
        '🚀 planner speed wave: retry=repair stream=on stream_idle=30s stream_total=1200s …',
        '🛰 planner client: provider_row=<ai_models id> stream_idle=30s stream_total=1200s http_ceiling=600s …  ← class 37 (per trader)',
        '🧪 validator hints: N sites — condition tokens legal+live, rule tokens in-field',
        '📜 prompt/validator contract: N restrictions, all stated in prompt  ← class 38',
        '⚖ arm normalizer: legs on non-sweep → single arm + WARN  ← class 39',
        '🔁 planner stream policy (class 41): stream_tries=3 backoff=2s→15s→45s watchdog_log=on keepalive=30s serialize_executor=off resend_identical=on  ← class 41 (per trader)',
        '🛡 cutover safety (class 33): flat gate legs=5 … leg4 reads the armed_orders LEDGER … boot sweep cancels pre-boot arms  ← class 33',
        '✂ planner schema: 9 top-level fields, ALL consumed … plan JSON ~920 tokens of a 23,769-token p50 output (3.9%); reasoning is ~96%  ← root-fix part A (measured, no cut shipped)',
        '🔬 shadow A/B (root-fix part B): OFF target_n=10 done=0 … promotion criterion: legal-rate ≥ max AND median wall ≤50% of max at n≥10',
        '🩹 repair (class 44): contract=full-doc restated head+tail · vocab-suffix=on · law excerpts=all-matching · outcomes recorded  ← class 44',
        '📊 bars: 1w nt8_agg via 1d since 2020-11-11 · 1d nt8 since 2020-11-11 · … · ladder(1w)=[1d 1m] · native 1w EXCLUDED · retention 1m=90d coarse=forever  ← class 45',
        '🛰 planner client: tries=3 backoff=2s→15s→45s keepalive_set=30s observed=n/a watchdog=pre600s/post90s(data) resend_identical=true serialize=false storm_cap=5 trace=true  ← class 49 (every field READ from its enforcer)',
        '⏱ watchdog fired: post gap=93.2s (limit 1m30s, call age 214.0s)  ← only when a generation actually stalls',
        '🔌 conn trace: closed_by=peer_fin reused=true bytes=54986 elapsed=250.1s  ← who ended the stream (INFERRED)',
        '🌩 storm cap reached: 5 provider call(s) this read ≥ cap 5  ← a 503 burst is not retried harder',
        '⚙ config diff (studio_save): min_risk_reward_ratio 3 → 2  ← one line per RESOLVED knob a save changed, plus a config_changes row',
        '🛡 boot sweep CANCELLED pre-boot arm (class 33): <session> <S#> … signal=<id> — the process that placed it is gone  ← only when a restart orphaned a resting order',
        '🎛 volume wave …   ← wave detector knobs',
        '🎯 touch telemetry …',
        '📐 fvg_entry …',
        '🔧 S-wave …',
        '',
        '+dirty usually = an untracked file (.env.bak…) — Go vcs.modified',
        'counts untracked files. NOT a code change.',
      ],
    },
    { kind: 'h', text: 'SYSTEM_STATUS strip (dashboard)' },
    {
      kind: 'table',
      head: ['Item', 'Meaning'],
      rows: [
        [
          'NT8 feed',
          'TCP bridge alive + bars flowing — the single source of truth.',
        ],
        ['Boot integrity', 'Running binary == deploy record (goldens PASS).'],
        ['Dead-man watchdog', 'Kernel heartbeats ok.'],
        ['Trader frozen', 'The trader loop is stuck — investigate.'],
        ['Clock drift', 'Host clock vs NT8 clock mismatch.'],
        [
          '402 banner',
          'An upstream model API returned HTTP 402 (billing) — the model is down for payment, not code.',
        ],
      ],
    },
    { kind: 'h', text: 'Gate-block labels — the full list' },
    {
      kind: 'code',
      title: 'every label the gate panel can show',
      lines: [
        'NT8 feed down · Dead-man watchdog · Trader frozen · Boot integrity',
        'Consecutive-loss halt · Past last-entry time · Outside session window',
        'Against the plan · Awaiting approval · Clock drift',
        'Duplicate order dropped · Order rate breaker · Burned level re-touched',
        'Night/day transition',
        '',
        'Reset: at the 17:00 session roll, and on bot restart.',
      ],
    },
    { kind: 'h', text: 'Stream cuts vs connection idleness' },
    {
      kind: 'p',
      text: "GET /api/risk/stream-cuts. Every early end of an AI stream — a peer FIN ('cut') or our own watchdog ('watchdog') — grouped by how long the connection had been idle before the call reused it, with what the identical resend then did. Born from 2026-09-03 08:11:38: a planner stream died to a peer FIN at 283.4s with 50,489 reasoning chars in, on a connection reused after 101,212ms idle; the resend that succeeded rode one idle 34,935ms. If cuts cluster above some idle threshold, setting IdleConnTimeout below it is the whole fix and needs nothing from the provider. NOTHING IS SET — the ruling was three more cuts before deciding. An unresolved resend counts as unresolved, never as a loss, and a connection that was not reused gets its own bucket so fresh dials never read as evidence about idleness. idle_before_ms and conn_reused ride every ai_call log line now, so this is greppable as well as queryable.",
    },
    { kind: 'h', text: 'Traffic light — one glance' },
    {
      kind: 'p',
      text: "GREEN = bot running, gates quiet, plan armed (or flat by plan). AMBER = gates firing repeatedly — read the ledger, don't override. RED = feed down / frozen / boot mismatch — use the emergency checklist (Section 9). The card's NO-TRADE banner is not a light: it is a state.",
    },
  ],
}
