import { GUIDE_BUILT_REV, type GuideSection } from '../types'

export const status: GuideSection = {
  id: 'status',
  num: 10,
  title: 'Status & Signals',
  tagline: 'Every indicator strip, banner, and log line — decoded.',
  asBuiltRev: GUIDE_BUILT_REV,
  blocks: [
    { kind: 'h', text: 'The boot ledger, line by line' },
    {
      kind: 'code',
      title: 'the lines printed at startup, in order',
      lines: [
        '🔐 BOOT INTEGRITY OK — rev <sha> [+dirty] · built <ts>',
        '🧾 P&L surfaces: <N> aggregators strict-corrected, 0 raw (corrected-column guard) — every P&L figure the model and the dashboard read is pnl_corrected; unresolved rows are counted and excluded, never coerced',
        '    · expected <sha> · goldens PASS      ← code matches deploy record',
        '📜 planner playbook: playbook=v2 bias_tree=on …',
        '🛡 plan facts guards: 0-side + empty map fail-closed …',
        '🚀 planner speed wave: retry=repair stream=on stream_idle=30s stream_total=1200s …',
        '🛰 planner client: provider_row=<ai_models id> stream_idle=30s stream_total=1200s http_ceiling=600s …  ← class 37 (per trader)',
        '🧪 validator hints: N sites — condition tokens legal+live, rule tokens in-field',
        '📜 prompt/validator contract: N restrictions, all stated in prompt  ← class 38',
        '⚖ arm normalizer: legs on non-sweep → single arm + WARN  ← class 39',
        '🔁 planner stream policy (class 41): stream_tries=3 backoff=2s→15s→45s watchdog_log=on keepalive=30s serialize_executor=off resend_identical=on  ← class 41 (per trader)',
        '🛡 cutover safety (class 33): flat gate legs=5 … leg4 reads the armed_orders LEDGER … boot sweep cancels pre-boot arms  ← class 33',
        '🛡 boot sweep CANCELLED pre-boot arm (class 33): <session> <S#> … signal=<id> — the process that placed it is gone  ← only when a restart orphaned a resting order',
        '🎛 volume wave …   ← wave detector knobs',
        '🎯 touch telemetry …',
        '📐 fvg_entry …',
        '🔧 S-wave …',
        '',
        '+dirty usually = an untracked file (.env.bak…) — Go vcs.modified',
        'counts untracked files. NOT a code change.',
      ],
    },
    { kind: 'h', text: 'SYSTEM_STATUS strip (dashboard)' },
    {
      kind: 'table',
      head: ['Item', 'Meaning'],
      rows: [
        [
          'NT8 feed',
          'TCP bridge alive + bars flowing — the single source of truth.',
        ],
        ['Boot integrity', 'Running binary == deploy record (goldens PASS).'],
        ['Dead-man watchdog', 'Kernel heartbeats ok.'],
        ['Trader frozen', 'The trader loop is stuck — investigate.'],
        ['Clock drift', 'Host clock vs NT8 clock mismatch.'],
        [
          '402 banner',
          'An upstream model API returned HTTP 402 (billing) — the model is down for payment, not code.',
        ],
      ],
    },
    { kind: 'h', text: 'Gate-block labels — the full list' },
    {
      kind: 'code',
      title: 'every label the gate panel can show',
      lines: [
        'NT8 feed down · Dead-man watchdog · Trader frozen · Boot integrity',
        'Consecutive-loss halt · Past last-entry time · Outside session window',
        'Against the plan · Awaiting approval · Clock drift',
        'Duplicate order dropped · Order rate breaker · Burned level re-touched',
        'Night/day transition',
        '',
        'Reset: at the 17:00 session roll, and on bot restart.',
      ],
    },
    { kind: 'h', text: 'Traffic light — one glance' },
    {
      kind: 'p',
      text: "GREEN = bot running, gates quiet, plan armed (or flat by plan). AMBER = gates firing repeatedly — read the ledger, don't override. RED = feed down / frozen / boot mismatch — use the emergency checklist (Section 9). The card's NO-TRADE banner is not a light: it is a state.",
    },
  ],
}
