#!/usr/bin/env bash
# crypto-union-gate.sh — the C13 union gate (plan v10 FINAL; DS-102 owns it).
#
# READ-ONLY over the repo. Writes only a /tmp scratch listing for the
# enumeration (mktemp + trap), never the tree, the DB or the box.
#
# Usage:  scripts/crypto-union-gate.sh <table-A> <table-B> <table-C>
#
# TABLE FORMAT (generated by the builders; reviewed before code):
#   branch-point: <40-hex sha>          # the part's branch point
#   integrator-tip: <40-hex sha>        # the integrator tip it was generated against
#   paths: <space-separated pathspecs>  # the part's swept paths
#   regex: <the assembled literal>      # MUST equal the guard's export, byte-for-byte
#   # rows, one per line (a "#" prefix is a comment / header):
#   path<TAB>token<TAB>DELETE|CUT|KEEP<TAB>reason
#   # a table with zero rows writes an explicit line instead:
#   0 hits
#
# Gate rules (C13 invariants 1-5 + the CTO's 2026-10-01 content-asserts):
#   (1) every table exists and parses: >=1 row or the explicit "0 hits" line.
#   (2) two shas: `git merge-base --is-ancestor <branch-point> HEAD` holds AND
#       `git diff --name-only <integrator-tip>..HEAD -- <paths>` is empty.
#   (3) git failure = FAIL, never a skip.
#   (4) canary: every KEEP row's token is re-found by the sweep in its file;
#       if the union holds NO KEEP rows, the guard test's sentinels are the
#       canary (printed as n/a here).
#   (5) ONE regex: each table's `regex:` header equals the guard's exported
#       literal (extracted programmatically from branding/no_crypto.go), byte
#       for byte — a hand-typed copy fails.
#   Sweep: git ls-files -z, >=2000-file floor, GNU grep -E -i -I (binary
#   files skipped). Every hit line is either gone or covered by a KEEP row
#   naming the file and a token the line contains (case-insensitive).
#   Content asserts (single-quoted 'mixed' sites the regex cannot see):
#       web/src/components/plan/ExecutorVerdict.tsx   arm.state === 'mixed'      -> must be PRESENT with a KEEP row
#       web/src/components/trader/TraderConfigModal.tsx source_type === 'mixed'  -> if present, must carry a CUT row; absent = cut complete
set -u

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$REPO_ROOT" || exit 3
GUARD=branding/no_crypto.go

fail=0
ok()   { echo "PASS $1"; }
bad()  { echo "FAIL $1"; fail=$((fail+1)); }

# -- regex literal, extracted PROGRAMMATICALLY from the guard (never re-typed)
lit=$(sed -n 's/^const SweepRegexLiteral = `\(.*\)`$/\1/p' "$GUARD")
if [ -z "$lit" ]; then bad "cannot extract SweepRegexLiteral from $GUARD"; echo "== $fail FAIL"; exit 1; fi
ok "sweep literal extracted from the guard ($(printf %s "$lit" | wc -c) bytes)"

# -- sweep the tracked tree (invariant 3 + the 2000 floor)
LIST=$(mktemp) || { bad "mktemp failed"; echo "== $fail FAIL"; exit 1; }
trap 'rm -f "$LIST"' EXIT
git ls-files -z > "$LIST" || { bad "git ls-files failed (never skip)"; echo "== $fail FAIL"; exit 1; }
nfiles=$(tr -cd '\0' < "$LIST" | wc -c)
if [ "$nfiles" -lt 2000 ]; then bad "enumeration floor: $nfiles tracked files < 2000"; fi
ok "enumerated $nfiles tracked files (floor 2000)"

declare -A keep_rows   # file|token -> reason
declare -A any_row
allrows=0; keepcount=0
for tbl in "$@"; do
  [ -f "$tbl" ] || { bad "table missing: $tbl"; continue; }
  bp=$(sed -n 's/^branch-point: *\([0-9a-f]\{40\}\)$/\1/p' "$tbl" | head -1)
  tip=$(sed -n 's/^integrator-tip: *\([0-9a-f]\{40\}\)$/\1/p' "$tbl" | head -1)
  paths=$(sed -n 's/^paths: *//p' "$tbl" | head -1)
  treg=$(sed -n 's/^regex: *//p' "$tbl" | head -1)
  [ -n "$bp" ] || bad "$tbl: header branch-point missing/not 40-hex"
  [ -n "$tip" ] || bad "$tbl: header integrator-tip missing/not 40-hex"
  [ -n "$paths" ] || bad "$tbl: header paths missing"
  if [ -n "$treg" ]; then
    if [ "$treg" = "$lit" ]; then ok "$tbl: regex header equals the guard literal byte-for-byte"; else
      bad "$tbl: regex header != guard literal (hand-typed copy?)"; fi
  else bad "$tbl: header regex missing"; fi
  if [ -n "$bp" ] && ! git merge-base --is-ancestor "$bp" HEAD 2>/dev/null; then
    bad "$tbl: HEAD does not descend from branch-point $bp"; fi
  if [ -n "$tip" ] && [ -n "$paths" ]; then
    d=$(git diff --name-only "$tip"..HEAD -- $paths 2>/dev/null)
    if [ -n "$d" ]; then bad "$tbl: stale table — diff $tip..HEAD over its paths is non-empty: $(echo "$d" | head -1)"; else
      ok "$tbl: diff $tip..HEAD over its paths is empty"; fi
  fi
  rows=$(grep -vE '^(#|branch-point:|integrator-tip:|paths:|regex:|0 hits$)' "$tbl")
  n=0
  while IFS=$'\t' read -r p tok disp reason; do
    [ -n "$p" ] || continue
    n=$((n+1)); allrows=$((allrows+1))
    any_row["$p"]=1
    case "$disp" in
      KEEP) keep_rows["$p|$tok"]="$reason"; keepcount=$((keepcount+1));;
      DELETE|CUT) ;;
      *) bad "$tbl: bad disposition '$disp' in row $p";;
    esac
  done <<EOF
$rows
EOF
  if [ "$n" -eq 0 ]; then
    grep -q '^0 hits' "$tbl" && ok "$tbl: explicit 0-hits table" || bad "$tbl: parses to 0 rows and no explicit '0 hits' line"
  else
    ok "$tbl: parses, $n rows"
  fi
done
[ "$allrows" -eq 0 ] && bad "union holds no rows and no table is an explicit 0-hits table"

# -- the sweep: every hit line is either gone or a KEEP row covers it
hits=0
while IFS= read -r -d '' f; do
  case "$f" in
    *_test.go) continue;;   # swept scope: Go *_test.go excluded
  esac
  out=$(grep -n -I -i -E "$lit" -- "$f" 2>/dev/null) || continue
  while IFS= read -r line; do
    hits=$((hits+1))
    covered=""
    for k in "${!keep_rows[@]}"; do
      p=${k%%|*}; tok=${k#*|}
      [ "$p" = "$f" ] || continue
      # token match: the row's token appears in the line, case-insensitive
      if printf '%s' "$line" | grep -qiF -- "$tok"; then covered="$k"; break; fi
    done
    if [ -n "$covered" ]; then continue; fi
    if [ "${any_row[$f]:-0}" = "1" ]; then
      bad "hit not covered by a KEEP row (DELETE/CUT rows must have removed it): $f: $(echo "$line" | cut -c1-90)"
    else
      bad "UNLISTED hit: $f: $(echo "$line" | cut -c1-90)"
    fi
  done <<EOF
$out
EOF
done < "$LIST"
ok "sweep complete: $hits hit lines, $keepcount KEEP rows in the union"

# -- invariant (4): canary over the union KEEP rows
can=0
for k in "${!keep_rows[@]}"; do
  p=${k%%|*}; tok=${k#*|}
  if [ -f "$p" ] && grep -q -I -i -F -- "$tok" "$p" 2>/dev/null; then can=$((can+1)); else
    bad "canary: KEEP row token '$tok' not re-found in $p — sweep or table is wrong"; fi
done
[ "$can" -gt 0 ] && ok "canary: all $can KEEP tokens re-found" || echo "NOTE canary n/a (no KEEP rows) — the guard test's sentinels are the canary"

# -- content asserts (CTO ruling 2026-10-01): single-quoted 'mixed' sites
f_keep="web/src/components/plan/ExecutorVerdict.tsx";  n_keep="arm.state === 'mixed'"
f_cut="web/src/components/trader/TraderConfigModal.tsx"; n_cut="source_type === 'mixed'"
if [ -f "$f_keep" ]; then
  if grep -qF -- "$n_keep" "$f_keep" 2>/dev/null; then
    k="${f_keep}|${n_keep}"
    [ -n "${keep_rows[$k]:-}" ] && ok "content-assert: ExecutorVerdict 'mixed' present with its KEEP row" \
      || bad "content-assert: ExecutorVerdict 'mixed' present but NO KEEP row names it"
  else bad "content-assert: ExecutorVerdict lost its plan-state 'mixed' line (KEEP site vanished)"; fi
else bad "content-assert: $f_keep missing at HEAD"; fi
if [ -f "$f_cut" ] && grep -qF -- "$n_cut" "$f_cut" 2>/dev/null; then
  if [ "${any_row[$f_cut]:-0}" = "1" ]; then
    ok "content-assert: TraderConfigModal 'mixed' still present but the table names it (CUT pending)"
  else bad "content-assert: TraderConfigModal 'mixed' present with NO row — a lane forgot the CUT"; fi
else
  ok "content-assert: TraderConfigModal 'mixed' gone (CUT complete)"
fi

echo "== $fail FAIL"
exit "$fail"
